name: Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        # To deploy official HTML forms from Financial Administration checkout with submodules
        # with:
        #  submodules: 'recursive'
      - name: Setup ssh
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo '-----BEGIN OPENSSH PRIVATE KEY-----' > ~/.ssh/deploy_pkey
          echo ${{ secrets.DEPLOY_PKEY }} >> ~/.ssh/deploy_pkey
          echo '-----END OPENSSH PRIVATE KEY-----' >> ~/.ssh/deploy_pkey
          chmod 400 ~/.ssh/deploy_pkey
          echo 'host ekosystem.staging.slovensko.digital' > ~/.ssh/config
          echo '  HostName ekosystem.staging.slovensko.digital' >> ~/.ssh/config
          echo '  IdentityFile ~/.ssh/deploy_pkey' >> ~/.ssh/config
          echo "ekosystem.staging.slovensko.digital ${{ secrets.DEPLOY_HOST_KEY }}" > ~/.ssh/known_hosts

      - name: Setup staging git
        if: github.ref == 'refs/heads/master'
        run: git remote add staging dokku@ekosystem.staging.slovensko.digital:priznanie-digital

      - name: Deploy to priznanie.staging.slovensko.digital
        if: github.ref == 'refs/heads/master'
        run: git push staging master:master --force
